import {expect, test, vi} from 'vitest';
import {main} from './index';
import * as getBaseSchemaModule from './getBaseSchema';

// Mock the getBaseSchema function
vi.mock('./getBaseSchema', () => ({
	getBaseSchema: vi.fn(),
}));

const mockGetBaseSchema = vi.mocked(getBaseSchemaModule.getBaseSchema);

test('main generates TypeScript code correctly', async () => {
	// GIVEN a comprehensive mock base schema with various field types and edge cases
	const mockBaseSchema = [
		{
			id: 'tblTest123',
			name: 'Test Table',
			fields: [
				{
					id: 'fld1',
					name: 'Name',
					type: 'singleLineText',
				},
				{
					id: 'fld2',
					name: '% amount',
					type: 'number',
					options: {precision: 2},
				},
				{
					id: 'fld3',
					name: '$ price',
					type: 'number',
					options: {precision: 2},
				},
				{
					id: 'fld4',
					name: '@ email',
					type: 'email',
				},
				{
					id: 'fld5',
					name: 'Status',
					type: 'singleSelect',
					options: {
						choices: [
							{id: 'sel1', name: 'Active', color: 'green'},
							{id: 'sel2', name: 'Inactive', color: 'red'},
						],
					},
				},
				{
					id: 'fld6',
					name: 'Multi-word Field Name',
					type: 'multilineText',
				},
				{
					id: 'fld7',
					name: 'Field with "quotes" and symbols!',
					type: 'singleLineText',
				},
				{
					id: 'fld8',
					name: '123 Numeric Start',
					type: 'number',
					options: {precision: 0},
				},
				{
					id: 'fld9',
					name: 'checkbox field',
					type: 'checkbox',
				},
				{
					id: 'fld10',
					name: 'Unsupported Field',
					type: 'unsupportedType',
				},
			],
		},
		{
			id: 'tblProjects',
			name: 'Projects',
			fields: [
				{
					id: 'fldProjName',
					name: 'Project Name',
					type: 'singleLineText',
				},
				{
					id: 'fldProjOwner',
					name: 'Owner',
					type: 'singleLineText',
				},
			],
		},
	];

	mockGetBaseSchema.mockResolvedValue(mockBaseSchema);

	const config = {
		apiKey: 'test-key',
		baseId: 'appTest123',
	};

	// WHEN we generate the code
	const result = await main(config);

	// THEN the generated code should match the snapshot
	expect(result).toMatchInlineSnapshot(`
		"/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
		/* eslint-disable */
		import type { Item, Table } from 'airtable-ts';

		export interface TestTable extends Item {
		  id: string,
		  name: string | null, // Original field: "Name"
		  amount: number | null, // Original field: "% amount"
		  price: number | null, // Original field: "$ price"
		  email: string | null, // Original field: "@ email"
		  status: string | null, // Original field: "Status"
		  multiWordFieldName: string | null, // Original field: "Multi-word Field Name"
		  fieldWithQuotesAndSymbols: string | null, // Original field: "Field with "quotes" and symbols!"
		  _123numericstart: number | null, // Original field: "123 Numeric Start"
		  checkboxField: boolean, // Original field: "checkbox field"
		  // Unsupported field "Unsupported Field" of type unsupportedType
		}

		export const TestTabletable: Table<TestTable> = {
		  name: 'Test Table',
		  baseId: 'appTest123',
		  tableId: 'tblTest123',
		  mappings: {
		    name: 'fld1', // Original field: "Name"
		    amount: 'fld2', // Original field: "% amount"
		    price: 'fld3', // Original field: "$ price"
		    email: 'fld4', // Original field: "@ email"
		    status: 'fld5', // Original field: "Status"
		    multiWordFieldName: 'fld6', // Original field: "Multi-word Field Name"
		    fieldWithQuotesAndSymbols: 'fld7', // Original field: "Field with "quotes" and symbols!"
		    _123numericstart: 'fld8', // Original field: "123 Numeric Start"
		    checkboxField: 'fld9', // Original field: "checkbox field"
		    // Unsupported field "Unsupported Field": fld10
		  },
		  schema: {
		    name: 'string | null',
		    amount: 'number | null',
		    price: 'number | null',
		    email: 'string | null',
		    status: 'string | null',
		    multiWordFieldName: 'string | null',
		    fieldWithQuotesAndSymbols: 'string | null',
		    _123numericstart: 'number | null',
		    checkboxField: 'boolean',
		  },
		};

		export interface Project extends Item {
		  id: string,
		  projectName: string | null, // Original field: "Project Name"
		  owner: string | null, // Original field: "Owner"
		}

		export const projectsTable: Table<Project> = {
		  name: 'Projects',
		  baseId: 'appTest123',
		  tableId: 'tblProjects',
		  mappings: {
		    projectName: 'fldProjName', // Original field: "Project Name"
		    owner: 'fldProjOwner', // Original field: "Owner"
		  },
		  schema: {
		    projectName: 'string | null',
		    owner: 'string | null',
		  },
		};"
	`);

	// Verify the mock was called correctly
	expect(mockGetBaseSchema).toHaveBeenCalledWith('appTest123', config);
});

test('main handles duplicate field names with numbering', async () => {
	// GIVEN a mock base schema with fields that would create duplicate identifiers
	const mockBaseSchema = [
		{
			id: 'tblDuplicates',
			name: 'Duplicate Test',
			fields: [
				{
					id: 'fld1',
					name: '% amount',
					type: 'number',
					options: {precision: 2},
				},
				{
					id: 'fld2',
					name: '$ amount',
					type: 'number',
					options: {precision: 2},
				},
				{
					id: 'fld3',
					name: '@ amount',
					type: 'number',
					options: {precision: 2},
				},
				{
					id: 'fld4',
					name: '# amount',
					type: 'number',
					options: {precision: 2},
				},
			],
		},
	];

	mockGetBaseSchema.mockResolvedValue(mockBaseSchema);

	const config = {
		apiKey: 'test-key',
		baseId: 'appDuplicates',
	};

	// WHEN we generate the code
	const result = await main(config);

	// THEN the generated code should handle duplicates with numbering
	expect(result).toMatchInlineSnapshot(`
		"/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
		/* eslint-disable */
		import type { Item, Table } from 'airtable-ts';

		export interface DuplicateTest extends Item {
		  id: string,
		  amount: number | null, // Original field: "% amount"
		  amount2: number | null, // Original field: "$ amount"
		  amount3: number | null, // Original field: "@ amount"
		  amount4: number | null, // Original field: "# amount"
		}

		export const DuplicateTesttable: Table<DuplicateTest> = {
		  name: 'Duplicate Test',
		  baseId: 'appDuplicates',
		  tableId: 'tblDuplicates',
		  mappings: {
		    amount: 'fld1', // Original field: "% amount"
		    amount2: 'fld2', // Original field: "$ amount"
		    amount3: 'fld3', // Original field: "@ amount"
		    amount4: 'fld4', // Original field: "# amount"
		  },
		  schema: {
		    amount: 'number | null',
		    amount2: 'number | null',
		    amount3: 'number | null',
		    amount4: 'number | null',
		  },
		};"
	`);

	// Verify the mock was called correctly
	expect(mockGetBaseSchema).toHaveBeenCalledWith('appDuplicates', config);
});
